TEMPLATE = \
	lib

CONFIG -= \
	qt

CONFIG += \
	staticlib

QMAKE_CXXFLAGS += \
	-std=c++11

TARGET = \
	lnetlib

DEPENDPATH += \
	lnetlib \
	lnetlib/asio \
	lnetlib/asio/detail \
	lnetlib/asio/generic \
	lnetlib/asio/impl \
	lnetlib/asio/ip \
	lnetlib/asio/local \
	lnetlib/asio/posix \
	lnetlib/asio/ssl \
	lnetlib/asio/windows \
	lnetlib/asio/detail/impl \
	lnetlib/asio/generic/detail \
	lnetlib/asio/ip/detail \
	lnetlib/asio/ip/impl \
	lnetlib/asio/local/detail \
	lnetlib/asio/ssl/detail \
	lnetlib/asio/ssl/impl \
	lnetlib/asio/ssl/old \
	lnetlib/asio/ssl/old/detail

INCLUDEPATH += \
	lnetlib \
	lnetlib/asio \
	lnetlib/asio/detail \
	lnetlib/asio/impl \
	lnetlib/asio/detail/impl \
	lnetlib/asio/ip \
	lnetlib/asio/ip/impl \
	lnetlib/asio/ip/detail \
	lnetlib/asio/generic/detail \
	lnetlib/asio/local/detail

SOURCES += \
	lnetlib/server.cpp \
	lnetlib/client.cpp \
    lnetlib/istream.cpp \
	lnetlib/ostream.cpp \
    lnetlib/helper.cpp \
    lnetlib/connection.cpp \
    lnetlib/socket.cpp \
    lnetlib/socket_non_ssl.cpp \
    lnetlib/socket_ssl.cpp \
    lnetlib/client_session.cpp \
    lnetlib/client_session_non_ssl.cpp \
    lnetlib/client_session_ssl.cpp \
    lnetlib/server_session.cpp \
    lnetlib/server_session_non_ssl.cpp \
    lnetlib/server_session_ssl.cpp \
    lnetlib/encryption.cpp

HEADERS += \
	lnetlib/asio/async_result.hpp \
	lnetlib/asio/basic_datagram_socket.hpp \
	lnetlib/asio/basic_deadline_timer.hpp \
	lnetlib/asio/basic_io_object.hpp \
	lnetlib/asio/basic_raw_socket.hpp \
	lnetlib/asio/basic_seq_packet_socket.hpp \
	lnetlib/asio/basic_serial_port.hpp \
	lnetlib/asio/basic_signal_set.hpp \
	lnetlib/asio/basic_socket.hpp \
	lnetlib/asio/basic_socket_acceptor.hpp \
	lnetlib/asio/basic_socket_iostream.hpp \
	lnetlib/asio/basic_socket_streambuf.hpp \
	lnetlib/asio/basic_stream_socket.hpp \
	lnetlib/asio/basic_streambuf.hpp \
	lnetlib/asio/basic_streambuf_fwd.hpp \
	lnetlib/asio/basic_waitable_timer.hpp \
	lnetlib/asio/buffer.hpp \
	lnetlib/asio/buffered_read_stream.hpp \
	lnetlib/asio/buffered_read_stream_fwd.hpp \
	lnetlib/asio/buffered_stream.hpp \
	lnetlib/asio/buffered_stream_fwd.hpp \
	lnetlib/asio/buffered_write_stream.hpp \
	lnetlib/asio/buffered_write_stream_fwd.hpp \
	lnetlib/asio/buffers_iterator.hpp \
	lnetlib/asio/completion_condition.hpp \
	lnetlib/asio/connect.hpp \
	lnetlib/asio/coroutine.hpp \
	lnetlib/asio/datagram_socket_service.hpp \
	lnetlib/asio/deadline_timer.hpp \
	lnetlib/asio/deadline_timer_service.hpp \
	lnetlib/asio/error.hpp \
	lnetlib/asio/error_code.hpp \
	lnetlib/asio/handler_alloc_hook.hpp \
	lnetlib/asio/handler_continuation_hook.hpp \
	lnetlib/asio/handler_invoke_hook.hpp \
	lnetlib/asio/handler_type.hpp \
	lnetlib/asio/high_resolution_timer.hpp \
	lnetlib/asio/io_service.hpp \
	lnetlib/asio/is_read_buffered.hpp \
	lnetlib/asio/is_write_buffered.hpp \
	lnetlib/asio/placeholders.hpp \
	lnetlib/asio/raw_socket_service.hpp \
	lnetlib/asio/read.hpp \
	lnetlib/asio/read_at.hpp \
	lnetlib/asio/read_until.hpp \
	lnetlib/asio/seq_packet_socket_service.hpp \
	lnetlib/asio/serial_port.hpp \
	lnetlib/asio/serial_port_base.hpp \
	lnetlib/asio/serial_port_service.hpp \
	lnetlib/asio/signal_set.hpp \
	lnetlib/asio/signal_set_service.hpp \
	lnetlib/asio/socket_acceptor_service.hpp \
	lnetlib/asio/socket_base.hpp \
	lnetlib/asio/spawn.hpp \
	lnetlib/asio/ssl.hpp \
	lnetlib/asio/steady_timer.hpp \
	lnetlib/asio/strand.hpp \
	lnetlib/asio/stream_socket_service.hpp \
	lnetlib/asio/streambuf.hpp \
	lnetlib/asio/system_error.hpp \
	lnetlib/asio/system_timer.hpp \
	lnetlib/asio/thread.hpp \
	lnetlib/asio/time_traits.hpp \
	lnetlib/asio/unyield.hpp \
	lnetlib/asio/use_future.hpp \
	lnetlib/asio/version.hpp \
	lnetlib/asio/wait_traits.hpp \
	lnetlib/asio/waitable_timer_service.hpp \
	lnetlib/asio/write.hpp \
	lnetlib/asio/write_at.hpp \
	lnetlib/asio/yield.hpp \
	lnetlib/asio/detail/addressof.hpp \
	lnetlib/asio/detail/array.hpp \
	lnetlib/asio/detail/array_fwd.hpp \
	lnetlib/asio/detail/assert.hpp \
	lnetlib/asio/detail/atomic_count.hpp \
	lnetlib/asio/detail/base_from_completion_cond.hpp \
	lnetlib/asio/detail/bind_handler.hpp \
	lnetlib/asio/detail/buffer_resize_guard.hpp \
	lnetlib/asio/detail/buffer_sequence_adapter.hpp \
	lnetlib/asio/detail/buffered_stream_storage.hpp \
	lnetlib/asio/detail/call_stack.hpp \
	lnetlib/asio/detail/chrono_time_traits.hpp \
	lnetlib/asio/detail/completion_handler.hpp \
	lnetlib/asio/detail/config.hpp \
	lnetlib/asio/detail/consuming_buffers.hpp \
	lnetlib/asio/detail/cstdint.hpp \
	lnetlib/asio/detail/date_time_fwd.hpp \
	lnetlib/asio/detail/deadline_timer_service.hpp \
	lnetlib/asio/detail/dependent_type.hpp \
	lnetlib/asio/detail/descriptor_ops.hpp \
	lnetlib/asio/detail/descriptor_read_op.hpp \
	lnetlib/asio/detail/descriptor_write_op.hpp \
	lnetlib/asio/detail/dev_poll_reactor.hpp \
	lnetlib/asio/detail/epoll_reactor.hpp \
	lnetlib/asio/detail/event.hpp \
	lnetlib/asio/detail/eventfd_select_interrupter.hpp \
	lnetlib/asio/detail/fd_set_adapter.hpp \
	lnetlib/asio/detail/fenced_block.hpp \
	lnetlib/asio/detail/function.hpp \
	lnetlib/asio/detail/gcc_arm_fenced_block.hpp \
	lnetlib/asio/detail/gcc_hppa_fenced_block.hpp \
	lnetlib/asio/detail/gcc_sync_fenced_block.hpp \
	lnetlib/asio/detail/gcc_x86_fenced_block.hpp \
	lnetlib/asio/detail/handler_alloc_helpers.hpp \
	lnetlib/asio/detail/handler_cont_helpers.hpp \
	lnetlib/asio/detail/handler_invoke_helpers.hpp \
	lnetlib/asio/detail/handler_tracking.hpp \
	lnetlib/asio/detail/handler_type_requirements.hpp \
	lnetlib/asio/detail/hash_map.hpp \
	lnetlib/asio/detail/io_control.hpp \
	lnetlib/asio/detail/keyword_tss_ptr.hpp \
	lnetlib/asio/detail/kqueue_reactor.hpp \
	lnetlib/asio/detail/limits.hpp \
	lnetlib/asio/detail/local_free_on_block_exit.hpp \
	lnetlib/asio/detail/macos_fenced_block.hpp \
	lnetlib/asio/detail/mutex.hpp \
	lnetlib/asio/detail/noncopyable.hpp \
	lnetlib/asio/detail/null_event.hpp \
	lnetlib/asio/detail/null_fenced_block.hpp \
	lnetlib/asio/detail/null_mutex.hpp \
	lnetlib/asio/detail/null_reactor.hpp \
	lnetlib/asio/detail/null_signal_blocker.hpp \
	lnetlib/asio/detail/null_socket_service.hpp \
	lnetlib/asio/detail/null_static_mutex.hpp \
	lnetlib/asio/detail/null_thread.hpp \
	lnetlib/asio/detail/null_tss_ptr.hpp \
	lnetlib/asio/detail/object_pool.hpp \
	lnetlib/asio/detail/old_win_sdk_compat.hpp \
	lnetlib/asio/detail/op_queue.hpp \
	lnetlib/asio/detail/operation.hpp \
	lnetlib/asio/detail/pipe_select_interrupter.hpp \
	lnetlib/asio/detail/pop_options.hpp \
	lnetlib/asio/detail/posix_event.hpp \
	lnetlib/asio/detail/posix_fd_set_adapter.hpp \
	lnetlib/asio/detail/posix_mutex.hpp \
	lnetlib/asio/detail/posix_signal_blocker.hpp \
	lnetlib/asio/detail/posix_static_mutex.hpp \
	lnetlib/asio/detail/posix_thread.hpp \
	lnetlib/asio/detail/posix_tss_ptr.hpp \
	lnetlib/asio/detail/push_options.hpp \
	lnetlib/asio/detail/reactive_descriptor_service.hpp \
	lnetlib/asio/detail/reactive_null_buffers_op.hpp \
	lnetlib/asio/detail/reactive_serial_port_service.hpp \
	lnetlib/asio/detail/reactive_socket_accept_op.hpp \
	lnetlib/asio/detail/reactive_socket_connect_op.hpp \
	lnetlib/asio/detail/reactive_socket_recv_op.hpp \
	lnetlib/asio/detail/reactive_socket_recvfrom_op.hpp \
	lnetlib/asio/detail/reactive_socket_recvmsg_op.hpp \
	lnetlib/asio/detail/reactive_socket_send_op.hpp \
	lnetlib/asio/detail/reactive_socket_sendto_op.hpp \
	lnetlib/asio/detail/reactive_socket_service.hpp \
	lnetlib/asio/detail/reactive_socket_service_base.hpp \
	lnetlib/asio/detail/reactor.hpp \
	lnetlib/asio/detail/reactor_fwd.hpp \
	lnetlib/asio/detail/reactor_op.hpp \
	lnetlib/asio/detail/reactor_op_queue.hpp \
	lnetlib/asio/detail/regex_fwd.hpp \
	lnetlib/asio/detail/resolve_endpoint_op.hpp \
	lnetlib/asio/detail/resolve_op.hpp \
	lnetlib/asio/detail/resolver_service.hpp \
	lnetlib/asio/detail/resolver_service_base.hpp \
	lnetlib/asio/detail/scoped_lock.hpp \
	lnetlib/asio/detail/scoped_ptr.hpp \
	lnetlib/asio/detail/select_interrupter.hpp \
	lnetlib/asio/detail/select_reactor.hpp \
	lnetlib/asio/detail/service_registry.hpp \
	lnetlib/asio/detail/shared_ptr.hpp \
	lnetlib/asio/detail/signal_blocker.hpp \
	lnetlib/asio/detail/signal_handler.hpp \
	lnetlib/asio/detail/signal_init.hpp \
	lnetlib/asio/detail/signal_op.hpp \
	lnetlib/asio/detail/signal_set_service.hpp \
	lnetlib/asio/detail/socket_holder.hpp \
	lnetlib/asio/detail/socket_ops.hpp \
	lnetlib/asio/detail/socket_option.hpp \
	lnetlib/asio/detail/socket_select_interrupter.hpp \
	lnetlib/asio/detail/socket_types.hpp \
	lnetlib/asio/detail/solaris_fenced_block.hpp \
	lnetlib/asio/detail/static_mutex.hpp \
	lnetlib/asio/detail/std_event.hpp \
	lnetlib/asio/detail/std_mutex.hpp \
	lnetlib/asio/detail/std_static_mutex.hpp \
	lnetlib/asio/detail/std_thread.hpp \
	lnetlib/asio/detail/strand_service.hpp \
	lnetlib/asio/detail/task_io_service.hpp \
	lnetlib/asio/detail/task_io_service_operation.hpp \
	lnetlib/asio/detail/task_io_service_thread_info.hpp \
	lnetlib/asio/detail/thread.hpp \
	lnetlib/asio/detail/thread_info_base.hpp \
	lnetlib/asio/detail/throw_error.hpp \
	lnetlib/asio/detail/throw_exception.hpp \
	lnetlib/asio/detail/timer_queue.hpp \
	lnetlib/asio/detail/timer_queue_base.hpp \
	lnetlib/asio/detail/timer_queue_ptime.hpp \
	lnetlib/asio/detail/timer_queue_set.hpp \
	lnetlib/asio/detail/timer_scheduler.hpp \
	lnetlib/asio/detail/timer_scheduler_fwd.hpp \
	lnetlib/asio/detail/tss_ptr.hpp \
	lnetlib/asio/detail/type_traits.hpp \
	lnetlib/asio/detail/variadic_templates.hpp \
	lnetlib/asio/detail/wait_handler.hpp \
	lnetlib/asio/detail/wait_op.hpp \
	lnetlib/asio/detail/weak_ptr.hpp \
	lnetlib/asio/detail/win_event.hpp \
	lnetlib/asio/detail/win_fd_set_adapter.hpp \
	lnetlib/asio/detail/win_fenced_block.hpp \
	lnetlib/asio/detail/win_iocp_handle_read_op.hpp \
	lnetlib/asio/detail/win_iocp_handle_service.hpp \
	lnetlib/asio/detail/win_iocp_handle_write_op.hpp \
	lnetlib/asio/detail/win_iocp_io_service.hpp \
	lnetlib/asio/detail/win_iocp_null_buffers_op.hpp \
	lnetlib/asio/detail/win_iocp_operation.hpp \
	lnetlib/asio/detail/win_iocp_overlapped_op.hpp \
	lnetlib/asio/detail/win_iocp_overlapped_ptr.hpp \
	lnetlib/asio/detail/win_iocp_serial_port_service.hpp \
	lnetlib/asio/detail/win_iocp_socket_accept_op.hpp \
	lnetlib/asio/detail/win_iocp_socket_connect_op.hpp \
	lnetlib/asio/detail/win_iocp_socket_recv_op.hpp \
	lnetlib/asio/detail/win_iocp_socket_recvfrom_op.hpp \
	lnetlib/asio/detail/win_iocp_socket_recvmsg_op.hpp \
	lnetlib/asio/detail/win_iocp_socket_send_op.hpp \
	lnetlib/asio/detail/win_iocp_socket_service.hpp \
	lnetlib/asio/detail/win_iocp_socket_service_base.hpp \
	lnetlib/asio/detail/win_iocp_thread_info.hpp \
	lnetlib/asio/detail/win_mutex.hpp \
	lnetlib/asio/detail/win_object_handle_service.hpp \
	lnetlib/asio/detail/win_static_mutex.hpp \
	lnetlib/asio/detail/win_thread.hpp \
	lnetlib/asio/detail/win_tss_ptr.hpp \
	lnetlib/asio/detail/wince_thread.hpp \
	lnetlib/asio/detail/winrt_async_manager.hpp \
	lnetlib/asio/detail/winrt_async_op.hpp \
	lnetlib/asio/detail/winrt_resolve_op.hpp \
	lnetlib/asio/detail/winrt_resolver_service.hpp \
	lnetlib/asio/detail/winrt_socket_connect_op.hpp \
	lnetlib/asio/detail/winrt_socket_recv_op.hpp \
	lnetlib/asio/detail/winrt_socket_send_op.hpp \
	lnetlib/asio/detail/winrt_ssocket_service.hpp \
	lnetlib/asio/detail/winrt_ssocket_service_base.hpp \
	lnetlib/asio/detail/winrt_timer_scheduler.hpp \
	lnetlib/asio/detail/winrt_utils.hpp \
	lnetlib/asio/detail/winsock_init.hpp \
	lnetlib/asio/detail/wrapped_handler.hpp \
	lnetlib/asio/generic/basic_endpoint.hpp \
	lnetlib/asio/generic/datagram_protocol.hpp \
	lnetlib/asio/generic/raw_protocol.hpp \
	lnetlib/asio/generic/seq_packet_protocol.hpp \
	lnetlib/asio/generic/stream_protocol.hpp \
	lnetlib/asio/impl/buffered_read_stream.hpp \
	lnetlib/asio/impl/buffered_write_stream.hpp \
	lnetlib/asio/impl/connect.hpp \
	lnetlib/asio/impl/io_service.hpp \
	lnetlib/asio/impl/read.hpp \
	lnetlib/asio/impl/read_at.hpp \
	lnetlib/asio/impl/read_until.hpp \
	lnetlib/asio/impl/serial_port_base.hpp \
	lnetlib/asio/impl/spawn.hpp \
	lnetlib/asio/impl/src.hpp \
	lnetlib/asio/impl/use_future.hpp \
	lnetlib/asio/impl/write.hpp \
	lnetlib/asio/impl/write_at.hpp \
	lnetlib/asio/ip/address.hpp \
	lnetlib/asio/ip/address_v4.hpp \
	lnetlib/asio/ip/address_v6.hpp \
	lnetlib/asio/ip/basic_endpoint.hpp \
	lnetlib/asio/ip/basic_resolver.hpp \
	lnetlib/asio/ip/basic_resolver_entry.hpp \
	lnetlib/asio/ip/basic_resolver_iterator.hpp \
	lnetlib/asio/ip/basic_resolver_query.hpp \
	lnetlib/asio/ip/host_name.hpp \
	lnetlib/asio/ip/icmp.hpp \
	lnetlib/asio/ip/multicast.hpp \
	lnetlib/asio/ip/resolver_query_base.hpp \
	lnetlib/asio/ip/resolver_service.hpp \
	lnetlib/asio/ip/tcp.hpp \
	lnetlib/asio/ip/udp.hpp \
	lnetlib/asio/ip/unicast.hpp \
	lnetlib/asio/ip/v6_only.hpp \
	lnetlib/asio/local/basic_endpoint.hpp \
	lnetlib/asio/local/connect_pair.hpp \
	lnetlib/asio/local/datagram_protocol.hpp \
	lnetlib/asio/local/stream_protocol.hpp \
	lnetlib/asio/posix/basic_descriptor.hpp \
	lnetlib/asio/posix/basic_stream_descriptor.hpp \
	lnetlib/asio/posix/descriptor_base.hpp \
	lnetlib/asio/posix/stream_descriptor.hpp \
	lnetlib/asio/posix/stream_descriptor_service.hpp \
	lnetlib/asio/ssl/basic_context.hpp \
	lnetlib/asio/ssl/context.hpp \
	lnetlib/asio/ssl/context_base.hpp \
	lnetlib/asio/ssl/context_service.hpp \
	lnetlib/asio/ssl/error.hpp \
	lnetlib/asio/ssl/rfc2818_verification.hpp \
	lnetlib/asio/ssl/stream.hpp \
	lnetlib/asio/ssl/stream_base.hpp \
	lnetlib/asio/ssl/stream_service.hpp \
	lnetlib/asio/ssl/verify_context.hpp \
	lnetlib/asio/ssl/verify_mode.hpp \
	lnetlib/asio/windows/basic_handle.hpp \
	lnetlib/asio/windows/basic_object_handle.hpp \
	lnetlib/asio/windows/basic_random_access_handle.hpp \
	lnetlib/asio/windows/basic_stream_handle.hpp \
	lnetlib/asio/windows/object_handle.hpp \
	lnetlib/asio/windows/object_handle_service.hpp \
	lnetlib/asio/windows/overlapped_ptr.hpp \
	lnetlib/asio/windows/random_access_handle.hpp \
	lnetlib/asio/windows/random_access_handle_service.hpp \
	lnetlib/asio/windows/stream_handle.hpp \
	lnetlib/asio/windows/stream_handle_service.hpp \
	lnetlib/asio/detail/impl/dev_poll_reactor.hpp \
	lnetlib/asio/detail/impl/epoll_reactor.hpp \
	lnetlib/asio/detail/impl/kqueue_reactor.hpp \
	lnetlib/asio/detail/impl/select_reactor.hpp \
	lnetlib/asio/detail/impl/service_registry.hpp \
	lnetlib/asio/detail/impl/strand_service.hpp \
	lnetlib/asio/detail/impl/task_io_service.hpp \
	lnetlib/asio/detail/impl/win_iocp_io_service.hpp \
	lnetlib/asio/detail/impl/winrt_timer_scheduler.hpp \
	lnetlib/asio/generic/detail/endpoint.hpp \
	lnetlib/asio/ip/detail/endpoint.hpp \
	lnetlib/asio/ip/detail/socket_option.hpp \
	lnetlib/asio/ip/impl/address.hpp \
	lnetlib/asio/ip/impl/address_v4.hpp \
	lnetlib/asio/ip/impl/address_v6.hpp \
	lnetlib/asio/ip/impl/basic_endpoint.hpp \
	lnetlib/asio/local/detail/endpoint.hpp \
	lnetlib/asio/ssl/detail/buffered_handshake_op.hpp \
	lnetlib/asio/ssl/detail/engine.hpp \
	lnetlib/asio/ssl/detail/handshake_op.hpp \
	lnetlib/asio/ssl/detail/io.hpp \
	lnetlib/asio/ssl/detail/openssl_init.hpp \
	lnetlib/asio/ssl/detail/openssl_types.hpp \
	lnetlib/asio/ssl/detail/password_callback.hpp \
	lnetlib/asio/ssl/detail/read_op.hpp \
	lnetlib/asio/ssl/detail/shutdown_op.hpp \
	lnetlib/asio/ssl/detail/stream_core.hpp \
	lnetlib/asio/ssl/detail/verify_callback.hpp \
	lnetlib/asio/ssl/detail/write_op.hpp \
	lnetlib/asio/ssl/impl/context.hpp \
	lnetlib/asio/ssl/impl/src.hpp \
	lnetlib/asio/ssl/old/basic_context.hpp \
	lnetlib/asio/ssl/old/context_service.hpp \
	lnetlib/asio/ssl/old/stream.hpp \
	lnetlib/asio/ssl/old/stream_service.hpp \
	lnetlib/asio/ssl/old/detail/openssl_context_service.hpp \
	lnetlib/asio/ssl/old/detail/openssl_operation.hpp \
	lnetlib/asio/ssl/old/detail/openssl_stream_service.hpp \
	lnetlib/asio/impl/error_code.ipp \
	lnetlib/asio/impl/handler_alloc_hook.ipp \
	lnetlib/asio/detail/impl/win_tss_ptr.ipp \
	lnetlib/asio/detail/impl/throw_error.ipp \
	lnetlib/asio/impl/error.ipp \
	lnetlib/asio/detail/impl/posix_tss_ptr.ipp \
	lnetlib/asio/detail/impl/winsock_init.ipp \
	lnetlib/asio/detail/impl/win_mutex.ipp \
	lnetlib/asio/detail/impl/posix_mutex.ipp \
	lnetlib/asio/detail/impl/service_registry.ipp \
	lnetlib/asio/detail/impl/win_thread.ipp \
	lnetlib/asio/detail/impl/posix_thread.ipp \
	lnetlib/asio/detail/impl/win_static_mutex.ipp \
	lnetlib/asio/detail/impl/handler_tracking.ipp \
	lnetlib/asio/detail/impl/timer_queue_set.ipp \
	lnetlib/asio/detail/impl/win_iocp_io_service.ipp \
	lnetlib/asio/detail/impl/win_event.ipp \
	lnetlib/asio/detail/impl/posix_event.ipp \
	lnetlib/asio/detail/impl/task_io_service.ipp \
	lnetlib/asio/detail/impl/socket_select_interrupter.ipp \
	lnetlib/asio/detail/impl/socket_ops.ipp \
	lnetlib/asio/detail/impl/eventfd_select_interrupter.ipp \
	lnetlib/asio/detail/impl/pipe_select_interrupter.ipp \
	lnetlib/asio/detail/impl/epoll_reactor.ipp \
	lnetlib/asio/detail/impl/kqueue_reactor.ipp \
	lnetlib/asio/detail/impl/dev_poll_reactor.ipp \
	lnetlib/asio/detail/impl/select_reactor.ipp \
	lnetlib/asio/impl/io_service.ipp \
	lnetlib/asio/detail/impl/buffer_sequence_adapter.ipp \
	lnetlib/asio/detail/impl/win_iocp_socket_service_base.ipp \
	lnetlib/asio/detail/impl/reactive_socket_service_base.ipp \
	lnetlib/asio/detail/impl/winrt_timer_scheduler.ipp \
	lnetlib/asio/detail/impl/timer_queue_ptime.ipp \
	lnetlib/asio/detail/impl/winrt_ssocket_service_base.ipp \
	lnetlib/asio/ip/impl/address_v4.ipp \
	lnetlib/asio/ip/impl/address_v6.ipp \
	lnetlib/asio/ip/impl/address.ipp \
	lnetlib/asio/ip/detail/impl/endpoint.ipp \
	lnetlib/asio/detail/impl/resolver_service_base.ipp \
	lnetlib/asio/impl/serial_port_base.ipp \
	lnetlib/asio/detail/impl/descriptor_ops.ipp \
	lnetlib/asio/detail/impl/reactive_descriptor_service.ipp \
	lnetlib/asio/detail/impl/reactive_serial_port_service.ipp \
	lnetlib/asio/detail/impl/signal_set_service.ipp \
	lnetlib/asio/detail/impl/strand_service.ipp \
	lnetlib/asio/detail/impl/win_iocp_handle_service.ipp \
	lnetlib/asio/detail/impl/win_iocp_serial_port_service.ipp \
	lnetlib/asio/detail/impl/win_object_handle_service.ipp \
	lnetlib/asio/generic/detail/impl/endpoint.ipp \
	lnetlib/asio/ip/impl/host_name.ipp \
	lnetlib/asio/local/detail/impl/endpoint.ipp \
	lnetlib/server.h \
	lnetlib/client.h \
	lnetlib/ostream.h \
	lnetlib/istream.h \
    lnetlib/helper.h \
    lnetlib/connection.h \
    lnetlib/socket.h \
    lnetlib/socket_non_ssl.h \
    lnetlib/socket_ssl.h \
    lnetlib/server_session.h \
    lnetlib/server_session_non_ssl.h \
    lnetlib/server_session_ssl.h \
    lnetlib/client_session.h \
    lnetlib/client_session_non_ssl.h \
    lnetlib/client_session_ssl.h \
    lnetlib/encryption.h \
    lnetlib/lsignal/lsignal.h \
    lnetlib/config.h
